### ISSUE TITLE
lgw_connect:555: ERROR: NOT EXPECTED CHIP VERSION (v255)

### ISSUE THREAD

**Issue by sheraz045** [Lora-net/lora_gateway#159]
When running util_spi_stress test I get the following error
root# util_spi_stress
INFO: Starting LoRa concentrator SPI stress-test number 1
Note: SPI port opened and configured ok
Note: SPI read success
lgw_connect:532: INFO: no FPGA detected or version not supported (v255)
Note: SPI read success
lgw_connect:555: ERROR: NOT EXPECTED CHIP VERSION (v255)
ERROR: lgw_connect() did not return SUCCESS

**Comment by sp193** [comment]
When you have issues getting the registers read, have you checked that a compatible board is connected properly and powered on, the reset and CS lines (e.g. for CS0, since ``/dev/spidev0.0`` is used by ``loragw_spi.native.c``) are connected, and you have reset the board (e.g. with ``reset_lgw.sh``)?
