### ISSUE TITLE
LBT + AFA handling

### ISSUE THREAD

**Issue by queifaro** [Lora-net/lora_gateway#87]
Hi All,
in a pktfwd code the LBT+AFA json parameters are parsed and passed to the gw hall.

The following is a LBT+AFA part of json conf 

       "lbt_cfg": {
            "enable": false,
            "rssi_target": -80, /* dBm */
            "chan_cfg":[ /* 8 channels maximum */
                { "freq_hz": 867100000, "scan_time_us": 128 },
                { "freq_hz": 867300000, "scan_time_us": 5000 },
                { "freq_hz": 867500000, "scan_time_us": 128 },
                { "freq_hz": 869525000, "scan_time_us": 128 }
            ],
            "sx127x_rssi_offset": -4 /* dB */
        },

so these are the frequency where the GW perform scan for the amount of microseconds configured in scan_time
Wath the meaning of rssi_target ? threshold in dbm to assert channel busy ?
and also how is performed the frequency change (AFA) if the channel is not free for the configured scan time ? or actually AFA is not yet implemented ?

How pktfwd will be informed if all the AFA changed frequency are not usable ? (i think that in this case pktfwd have to inform net server with a certain code in NS to GW protocol....) 
Thanks in advance
B/R

**Comment by larkolab** [comment]
Hello,

The rssi_target is the threshold in dbm to assert channel busy, yes.

If the channel is busy, the downlink request is rejected, there is no AFA.

Today, the server is not informed by the packet forwarder if a downlink has been rejected due to LBT. The issue is that the LBT check is done just before actually sending the packet over the air, whereas the feedback to the network server about downlink rejection is done when inserting the downlink in the Just-in-Time queue.
So a Gateway/NetworkServer protocol change would be required to report a downlink rejected to the NS asynchronously. It is not planned to be done yet.

Best regards,
Michael
